version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout

      - type: cache-restore
        keys:
          - v1-dependencies-bundler-{ { checksum "Gemfile.lock" }}
          - v1-dependencies-bundler-

      - run: gem install bundler --no-document
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - type: cache-save
        key: v1-dependencies-bundler-{ { checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake
  deploy:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout

      - type: cache-restore
        keys:
          - v1-dependencies-bundler-{ { checksum "Gemfile.lock" }}
          - v1-dependencies-bundler-

      - run: gem install bundler --no-document
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - type: cache-save
        key: v1-dependencies-bundler-{ { checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake

workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^[0-9].*/

  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9].*/
            branches:
              only: master

