name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - run: bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Build Gem
      run: bundle exec rake build
    - name: Publish to GPR
      run: |
        mkdir -p ${HOME}/.gem
        echo -e "---\n:github: ${GEM_HOST_API_KEY}" >$HOME/.gem/credentials
        chmod 0600 ${HOME}/.gem/credentials
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} pkg/*.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
